
export PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin'

export PS1="\W \$ "

export EDITOR=vim


alias grep="grep --color=always"
alias st="git status"
alias h="cd ~"
alias br="git branch"
alias df="git diff"
alias pl="git pull"
alias pu="git push"
alias ff="find . -type f -name"
alias fh="find ~ -type f -name"
alias fr="find / -type f -name"
alias search="find . -type f -print0 | xargs -0 grep -i"
