
export PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin'

export PS1="\W \$ "

export EDITOR=vim

# Alias
alias grep="grep --color=always"
alias st="git status"
alias h="cd ~"
alias br="git branch"
alias df="git diff"
alias pl="git pull"
alias pu="git push"
alias ff="find . -type f -name"
alias fh="find ~ -type f -name"
alias fr="find / -type f -name"
alias search="find . -type f -print0 | xargs -0 grep -i"


# Python
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
if [[ -r /usr/local/bin/virtualenvwrapper.sh ]]; then
    source /usr/local/bin/virtualenvwrapper.sh
else
    echo "WARNING: Can't find virtualenvwrapper.sh"
fi


